# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
inhibit_all_warnings!

target 'Test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Alamofire'
  pod 'Moya/RxSwift'
  pod 'SnapKit'
  pod 'DeviceKit'
  pod 'UITableView+FDTemplateLayoutCell'
  pod 'MJRefresh'
  pod 'SDCycleScrollView'
  pod 'SwifterSwift'
  
end
